### ISSUE TITLE
Error when running on a clean install

### ISSUE THREAD

**Issue by izxle** [ekraka/TS-GAN#1]
**Describe the bug**
On a clean install, the `predict.py` script gets errors.

**To Reproduce**
Steps to reproduce:
1. Clone the repository: `$ git clone https://github.com/ekraka/TS-GAN.git`
3. Create a new conda environment: `$ conda create -n GANTS python=3.11`
4. Install tensorflow: `$ pip install tensorflow`
5. Run the `predict.py` script with test `xyz` files. 

```python
$ python predict.py reactant.xyz product.xyz
Traceback (most recent call last):
  File "/Users/bruno/Documents/TS-GAN/test_cases/dataset-A/../../predict.py", line 20, in <module>
    from matplotlib import pyplot
ModuleNotFoundError: No module named 'matplotlib'
```

7. Install matplotlib `pip install matplotlib`
8. Run the `predict.py` script with test `xyz` files. `$ python predict.py reactant.xyz product.xyz`
9. See error.

The instruction to run the `predict.py` script say to add the `g_mode.h5` file to the working directory where the `xyz` files are but this error occurs before that is needed. I've tried it both ways and the same error is given.

**Expected behavior**
The example should run without errors.

**Error messages**

```python
$ python predict.py reactant.xyz product.xyz
2023-04-18 12:03:07.129911: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
(1, 50, 50, 2) (1, 50, 50, 2)
Loaded (1, 50, 50, 2) (1, 50, 50, 2)
...
<Many TensorFlow WARNINGS>
...
Traceback (most recent call last):
  File "/Users/bruno/Documents/TS-GAN/test_cases/dataset-A/../../predict.py", line 310, in <module>
    d_model = define_discriminator(image_shape)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bruno/Documents/TS-GAN/test_cases/dataset-A/../../predict.py", line 62, in define_discriminator
    model = Model([in_src_image, in_target_image], patch_out)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bruno/miniconda3/envs/GANTS_new/lib/python3.11/site-packages/tensorflow/python/trackable/base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bruno/miniconda3/envs/GANTS_new/lib/python3.11/site-packages/keras/engine/functional.py", line 159, in __init__
    [
  File "/Users/bruno/miniconda3/envs/GANTS_new/lib/python3.11/site-packages/keras/engine/functional.py", line 160, in <listcomp>
    functional_utils.is_input_keras_tensor(t)
  File "/Users/bruno/miniconda3/envs/GANTS_new/lib/python3.11/site-packages/keras/engine/functional_utils.py", line 49, in is_input_keras_tensor
    return tensor.node.is_input
           ^^^^^^^^^^^
AttributeError: 'KerasTensor' object has no attribute 'node'
```

**System information:**
- Operating System: macOS Ventura 13.2.1
- Python version: 3.11.2
- Tensorflow version: 2.12.0

**Additional Information**

I attach the test `xyz` files that I used (as `txt` because github doesn't recognize the xyz format).
[reactant.txt](https://github.com/ekraka/TS-GAN/files/11265055/reactant.txt)
[product.txt](https://github.com/ekraka/TS-GAN/files/11265056/product.txt)

**Comment by MZ-Makos** [comment]
Hello, 
You are using TensorFlow version: 2.12.0. The instruction says to use TensorFlow version 2.2.0. 
TensorFlow is an open-source machine-learning library developed by Google. At the time of writing TS-GAN, version 2.2.0 was the newest one. Recently Google released Tensorflow version 2.12.0. 

Our code will be updated as well in the near future. However, for now, the recommendation is to create a new Conda environment and install:
pip install tensorflow==2.2.0

This will solve your error. 

Best regards, 
Malgorzata 

P.S. Prerequisites also say to use Python version 3.8.0

**Comment by izxle** [comment]
Hello, thank you for your prompt response. We were able to run it, although it wasn't straightforward.

We did try it with the specified versions before but since we got other errors we first tried with the updated ones.

Here's what we did and the errors we got before having it running.

First, we prepared the environment:

```sh
$ conda create -n GANTS python=3.8
$ conda activate GANTS
$ pip install tensorflow==2.2.0
$ pip install matplotlib
```

We then ran the script and got the following:

```sh
$ python predict.py reactant.xyz product.xyz
Traceback (most recent call last):
  File "predict.py", line 7, in <module>
    from tensorflow.keras.optimizers import Adam
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 53, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

We then downgraded protobuf as instructed `$ pip install protobuf==3.20.3`, but we got another error.

```sh
$ python predict.py reactant.xyz product.xyz
/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py:513: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  np.object,
Traceback (most recent call last):
  File "predict.py", line 7, in <module>
    from tensorflow.keras.optimizers import Adam
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 64, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/python/framework/framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 54, in <module>
    from tensorflow.python.framework import dtypes
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/tensorflow/python/framework/dtypes.py", line 513, in <module>
    np.object,
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
We tried to downgrade numpy, `$ pip install numpy==1.19.5`, 

```sh
$ pip install numpy==1.19.5
Collecting numpy==1.19.5
  Using cached numpy-1.19.5-cp38-cp38-macosx_10_9_x86_64.whl (15.6 MB)
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.2
    Uninstalling numpy-1.24.2:
      Successfully uninstalled numpy-1.24.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.7.1 requires numpy>=1.20, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5
$ python predict.py reactant.xyz product.xyz
Traceback (most recent call last):
  File "predict.py", line 20, in <module>
    from matplotlib import pyplot
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/matplotlib/__init__.py", line 229, in <module>
    _check_versions()
  File "/Users/bruno/miniconda3/envs/GANTS/lib/python3.8/site-packages/matplotlib/__init__.py", line 225, in _check_versions
    raise ImportError(f"Matplotlib requires {modname}>={minver}; "
ImportError: Matplotlib requires numpy>=1.20; you have 1.19.5
```

We then commented line 20 of the script (the only mention of matplotlib) and now the code ran without issues.

**Comment by MZ-Makos** [comment]
The predict.py script does not use Matplotlib; therefore, this line can be commented. 
I am still trying to understand why it didn't run in the first place. 
In my environment, I have: 
Python 3.8
numpy 1.20.0
matplotlib 3.7.1 
TensorFlow 2.2.0

As I mentioned, we are working on updating the TS-GAN code with the newest versions of those libraries.

**Comment by izxle** [comment]
It might be because we're using Mac, we've been having many issues with code running differently
